# Generated by Django 5.0.7 on 2024-07-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='marca', max_length=100),
            preserve_default=False,
        ),
    ]
